version: "3.3"
services:
  app:
    container_name: strapi-postgres
    image: strapi-postgres
    restart: always
    build:
      context: .
    volumes: 
      - ./src:/app/src
    ports:
      - 172.17.0.1:1337:1337
    depends_on:
      - postgres
    environment:
      DOMAIN: https://strapi-postgres-u147.vm.appdrag.net
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: narayana@softsuave.com
      PGADMIN_DEFAULT_PASSWORD: strapi
      PGADMIN_LISTEN_PORT: 443
      PGADMIN_ENABLE_TLS: 1  
    ports:
      - "34343:443"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - /root/.acme.sh/vm.appdrag.net/fullchain.cer:/certs/server.cert
      - /root/.acme.sh/vm.appdrag.net/vm.appdrag.net.key:/certs/server.key