version: "3.3"
services:
  app:
    image: strapi
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '172.17.0.1:1337:1337'
    environment:
      DOMAIN: https://[CI_CD_DOMAIN]
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '172.17.0.1:25432:5432'
      
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - /root/.acme.sh/vm.appdrag.net/fullchain.cer:/certs/server.cert
      - /root/.acme.sh/vm.appdrag.net/vm.appdrag.net.key:/certs/server.key